[package]
name = "gkr-implementation"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
evaluation_form_poly = { git = "https://github.com/BiliqisO/zk-implementations.git", branch = "main", package = "multilinear-polynomial" }