[package]
name = "shamir-secret-sharing-threshhold-scheme"
version = "0.1.0"
edition = "2021"

[dependencies]
zkpolynomial = "0.1.3"
rand = "0.8"
lazy_static = "1.4"
ark-ff = "0.5.0"
ark-bn254 = "0.5.0"
ark-std = "0.5.0"
